export const queryKeys = {
  me: ['me'],
  departments: (filters) => ['departments', filters],
  categories: (filters) => ['categories', filters],
  emissionFactors: (filters) => ['emissionFactors', filters],
  products: (filters) => ['products', filters],
  goals: (filters) => ['goals', filters],
  policies: (filters) => ['policies', filters],
  policyAcknowledgements: (filters) => ['policyAcknowledgements', filters],
  badges: (filters) => ['badges', filters],
  rewards: (filters) => ['rewards', filters],
  scoringOverview: ['scoring', 'overview'],
  scoringDepartments: ['scoring', 'departments'],
  carbonList: (filters) => ['carbon', 'list', filters],
  carbonTrend: (months) => ['carbon', 'trend', months],
  carbonByDepartment: ['carbon', 'byDepartment'],
  csrActivities: (filters) => ['csr', 'activities', filters],
  csrQueue: (filters) => ['csr', 'queue', filters],
  challenges: (filters) => ['challenges', filters],
  challengeParticipation: (filters) => ['challenges', 'participation', filters],
  audits: (filters) => ['audits', filters],
  compliance: (filters) => ['compliance', filters],
  leaderboard: (filters) => ['leaderboard', filters],
  notifications: (filters) => ['notifications', filters],
  settings: ['settings'],
};
