export const SOCKET_EVENTS = {
  NOTIFICATION_NEW: 'NOTIFICATION_NEW',
  LEADERBOARD_UPDATE: 'LEADERBOARD_UPDATE',
  APPROVAL_NEW: 'APPROVAL_NEW',
  CARBON_NEW: 'CARBON_NEW',
  SCORE_UPDATED: 'SCORE_UPDATED',
  BADGE_UNLOCKED: 'BADGE_UNLOCKED',
};
